#ifndef RESOURCES_H
#define RESOURCES_H


enum Strategic {NO_STRATEGIC, IRON, HORSES, URANIUM, ALUMINUM, COAL, OIL};

enum Luxury {NO_LUXURY = 7, WHEAT = 8, CATTLE = 9, DEER = 10, FISH = 11, WHALES = 12,
             BANANAS = 13, GOLD_RESOURCE = 14, GEMS = 15, MARBLE = 16, IVORY = 17, DYES = 18,
             SPICES = 19, SILK = 20, SUGAR = 21, COTTON = 22, PEARLS = 23, INCENSE = 24,
             WINE = 25, SILVER = 26, FURS = 27, SHEEP = 28};

#endif // RESOURCES_H
