#ifndef TILEIMPROVEMENT_H
#define TILEIMPROVEMENT_H

enum TileImprovement
{
    FARM, ROAD, TRADE_POST, PLANTATION, MINE, PASTURE, FISHING_BOAT, OIL_WELL, QUARRY, CAMP, NONE
};

#endif // TILEIMPROVEMENT_H
