#ifndef UNITTYPE_H
#define UNITTYPE_H
#include <QString>

enum UnitType { WORKER, SETTLER, WARRIOR, ARCHER, SPEARMAN, PIKEMAN, HORSEMAN, SCOUT, HORSE_ARCHER, CATAPULT,
                TREBUCHET, TRIREME, GALLEY, KNIGHT, CROSSBOWMAN, LANDSNACK, LONGSWORDSMAN, SWORDSMAN, MUSKETMAN,
                RIFLEMAN, CARAVEL, CANNON, LANCER, CAVALRY, INFANTRY, FRIGATE, IRONCLAD, ARTILLERY, TANK,
                PARATROOPER, ANTI_TANK_GUN, AA, BATTLESHIP, DESTROYER, CARRIER, SUBMARINE, NUKE, MOBILE_SAM,
                HELICOPTER_GUNSHIP,MECHANIZED_INFANTRY, MODERN_ARMOR, FIGHTER, BOMBER, JET_FIGHTER, STEALTH_BOMBER, GDR, GANDHI_DR
              };

#endif // UNITTYPE_H
